name       : most
version    : 5.0.0a
release    : 2
source     :
    - http://www.jedsoft.org/releases/most/most-5.0.0a.tar.gz : 17a16593da064ddd484f53157d54b83bcd98ea45ab1ed361eea64c4fae163a10
license    : GPL-2.0
component  : system.utils
summary    : Why settle for less?
description: |
    Most is a powerful paging program for Unix, VMS, MSDOS, and win32 systems. Unlike other well-known paging programs most supports multiple windows and can scroll left and right.
builddeps  :
    - pkgconfig(slang)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
