name       : most
version    : 5.1.0
release    : 3
source     :
    - https://www.jedsoft.org/releases/most/most-5.1.0.tar.gz : db805d1ffad3e85890802061ac8c90e3c89e25afb184a794e03715a3ed190501
license    : GPL-2.0
component  : system.utils
summary    : Why settle for less?
description: |
    Most is a powerful paging program for Unix, VMS, MSDOS, and win32 systems. Unlike other well-known paging programs most supports multiple windows and can scroll left and right.
builddeps  :
    - pkgconfig(slang)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
